### ISSUE TITLE
Force SSL to true fails to start server

### ISSUE THREAD

**Issue by suipinglu** [anz-bank/sysl-go#113]
Hi all,

currently having an issue for enabling the SSL for the downstream.

the following the config yaml setting:
```
    abc:
      serviceURL: https://xxx.com
      clientTimeout: 120s
      clientTransport:
        useProxy: true
        clientTLS:
          insecureSkipVerify: false
```
when we start with these command:

```
./bffserver bff --config=config-dev.yaml
```

got the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x15171db]
goroutine 1 [running]:
github.com/anz-bank/sysl-go/config.TLSVersions(0xc000302910, 0xc000512270, 0x0, 0x0)
        /Users/xxxxxx/go/pkg/mod/github.com/anz-bank/sysl-go@v0.23.0/config/tls.go:103 +0x2b
github.com/anz-bank/sysl-go/config.MakeTLSConfig(0xc000302910, 0xc000377940, 0x20, 0x18)
        /Users/xxxxxx/go/pkg/mod/github.com/anz-bank/sysl-go@v0.23.0/config/tls.go:277 +0x73
github.com/anz-bank/sysl-go/config.defaultHTTPTransport(0x1e31858, 0x20, 0x1e31380, 0x1fa86d0)
        /Users/xxxxxx/go/pkg/mod/github.com/anz-bank/sysl-go@v0.23.0/config/http.go:110 +0x33
github.com/anz-bank/sysl-go/config.DefaultHTTPClient(0x1e31848, 0xc000377920, 0xc000277a20, 0x100e8a8)
        /Users/xxxxxx/go/pkg/mod/github.com/anz-bank/sysl-go@v0.23.0/config/http.go:136 +0x43
github.com/anz-bank/sysl-go/core.BuildDownstreamHTTPClient(0x183b3c8, 0x3, 0x1e31848, 0xc000397080, 0x0, 0x0)
        /Users/xxxxxx/go/pkg/mod/github.com/anz-bank/sysl-go@v0.23.0/core/downstreambuilder.go:17 +0x38
github.com/anzx/bah-bff/internal/bff.(*HandlerManager).LoadServices(0xc000370f40, 0x1952f40, 0xc000397050, 0x1e4d780, 0x16df420)
        /Users/xxxxxx/Development/bah-bff/internal/bff/bff.go:103 +0x6a6
github.com/anzx/bah-bff/internal/bff.(*Config).ListenAndServe(0x1e31740, 0x1743f20, 0x1e31740)
        /Users/xxxxxx/Development/bah-bff/internal/bff/bff.go:35 +0x1a0
github.com/anzx/bah-bff/internal/cmd.glob..func1(0x1e25f60, 0xc00024f9b0, 0x0, 0x1)
        /Users/xxxxxx/Development/bah-bff/internal/cmd/bff.go:106 +0xce
github.com/spf13/cobra.(*Command).execute(0x1e25f60, 0xc00024f980, 0x1, 0x1, 0x1e25f60, 0xc00024f980)
        /Users/xxxxxx/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1e31100, 0xc000277f30, 0x2, 0x2)
        /Users/xxxxxx/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/xxxxxx/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/anzx/bah-bff/internal/cmd.Execute()
        /Users/xxxxxx/Development/bah-bff/internal/cmd/root.go:72 +0x7d
main.main()
        /Users/xxxxxx/Development/bah-bff/cmd/bffserver/main.go:8 +0x20
```

any thought on this please, did i miss anything beforehand?
i have the crt installed on local already, crt has been tested with Postman collection and no issues.

Cheers

**Comment by uynap** [comment]
`MinVersion` and `MaxVersion` are required by sysl-go when `insecureSkipVerify: false`. 
@suipinglu you can change your yaml config file to blow:
```
    abc:
      serviceURL: https://xxx.com
      clientTimeout: 120s
      clientTransport:
        useProxy: true
        clientTLS:
          insecureSkipVerify: false
          min: "1.2"
          max: "1.3"
```

**Comment by suipinglu** [comment]
> `MinVersion` and `MaxVersion` are required by sysl-go when `insecureSkipVerify: false`.
> @suipinglu you can change your yaml config file to blow:
> 
> ```
>     abc:
>       serviceURL: https://xxx.com
>       clientTimeout: 120s
>       clientTransport:
>         useProxy: true
>         clientTLS:
>           insecureSkipVerify: false
>           min: "1.2"
>           max: "1.3"
> ```

Just tried, no luck.
The same output just like the above original thread.

**Comment by uynap** [comment]
try this config:
```
      clientTransport:
        clientTLS:
          insecureSkipVerify: false
          minVersion: "1.2"
          maxVersion: "1.3"
          clientAuth: "NoClientCert"
          serverIdentity:
            certKeyPair:
              certPath: ""
              KeyPath: ""
```

**Comment by uynap** [comment]
When you want to enable TLS support, you have to provide the complete information regarding to SSL. It include TLS settings and cert/key files. 
`certPath` and `KeyPath` are the files you need to provide.

**Comment by springwiz** [comment]
@suipinglu 
Try this 
```
clientTransport:
        clientTLS:
          insecureSkipVerify: false
          trustedCertPool:
            encoding: "pem"
            mode: "directory"
            path: "path to root and intermediate ca's folder"
          serverIdentity:
            certKeyPair:
              certPath: ""
              KeyPath: ""
```
