### ISSUE TITLE
Handle JSON-encoded errors returned in HTTP headers

### ISSUE THREAD

**Issue by gkanz** [anz-bank/sysl-go#13]
Some systems do not send an error body, instead they are located in a header:

```
'400':
  description: Bad Request
  headers:
    ErrorContext:
      type:  string
      description: 'JSON-encoded error response'
```
The SYSL code will generate a client method with 3 return types:

`func (s *Client) GetThingsList(ctx context.Context, req *GetThingsListRequest) (*GetThingsResponse, *error, error)`

Inside this method some of the 'return' statuments only have 2 return arguments:

```
ErrorResponse, ok := result.Response.(*error)
  if ok {
    valErr := validator.Validate(ErrorResponse)
    if valErr != nil {
      return nil, nil, common.CreateDownstreamError(ctx, common.DownstreamUnexpectedResponseError, result.HTTPResponse, result.Body, valErr)
    }
    return ErrorResponse, nil
  }
```

ErrorContext definition:
```
definitions:
  errorContext:
    type: object
    properties:
      Status:
        type: array
        items:
          $ref: '#/definitions/Status'
  Status:
    type: object
    properties:
      message:
        type: string
      code:
        type: string
```
