### ISSUE TITLE
Setup CI using Github Actions

### ISSUE THREAD

**Issue by cuminandpaprika** [anz-bank/sysl-go#6]
Setup Continuous Integration on this repo.

Requirements
- [x] Linting
    - Golangci-lint can be run several ways, either via reviewdog or codeclimate to get comments on the PR. Or it can be run directly as a check.
- [ ] Code Analysis
    - SonarCloud https://sonarcloud.io/dashboard?id=cuminandpaprika_sysl-go-comms
- [x] Run tests
- [x] Check Test coverage
- [x] Check go mod tidy doesn't modify any files
    - Something like https://blog.urth.org/2019/08/13/testing-go-mod-tidiness-in-ci/

Stretch Goals
- Spell check commit messages https://github.com/marketplace/actions/check-spelling
- Run and deploy example repo for preview, e.g https://zeit.co/github#features or heroku
- Automated Release Tagging
Blocked till https://github.com/anz-bank/sysl/issues/666 is closed
- Validate transform files with `sysl validate`
- Validate makefile keeps git state in porcelain state

**Comment by cuminandpaprika** [comment]
Investigations into Coveralls seem to prove that Go support is secondary, and documentation seems to be outdated. Refer to https://docs.coveralls.io/go
- Go support is user contributed and the docs are for an older version of Github Actions

Running with the following config
```
    - name: Publish test results to Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with: 
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./coverage.out
```

Produced these results:
```
[error] "2020-03-17T07:21:37.830Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2020-03-17T07:21:37.830Z"  'input: ' 'mode: set\n' +
```
https://github.com/cuminandpaprika/sysl-go-comms/pull/1/checks?check_run_id=513083763
